name = "HexFits"
uuid = "1465c6e1-1cbb-424f-a4d4-267027409048"
authors = ["James C. McGarry <j.mcgarry@herts.ac.uk>"]
version = "0.1.0"

[deps]
FITSFiles = "358a0a88-3548-4ad6-b652-8bdbf64af8e5"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
FITSFiles = "0.3.2"
Statistics = "1.11.1"
